### PR TITLE
Fixed issue #67

### PR DESCRIPTION
**Pull request by MrDomani**
Do funkcji plot.break_down i plot.break_down_uncertainty użytkownik może podać argumenty title i subtitle. Domyślnie ustawione tak, jak w opisie issue. Pokryte testami i opisane w dokumentacji.

### CODE REVIEW

**Comment by pbiecek** [comment]
Thank you.
Can you please change the `title` and `subtitle` to normal arguments that are listed in the `plot.break_down()` function. 
So the signature will be 
```
plot.break_down(x, ..., title = "default value...", subtitle = "default value...")
```
This way the code will be simpler (no need to extract these arguments from `...`).

**Comment by MrDomani** [comment]
Done.

**Comment by pbiecek** [comment]
@MrDomani please note that Travis returns an error for this pull request:
https://travis-ci.org/ModelOriented/iBreakDown/builds/654052631?utm_source=github_status&utm_medium=notification

**Comment by MrDomani** [comment]
Checks have passed.

**Pull request merged**
